apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busypod
    app: mysql
  name: busypod
spec:
  containers:
  - image: busybox
    name: busypod
    command:
    - /bin/sh 
    - -c 
    - while true; do sleep 60; done;
  restartPolicy: Always
status: {}
