apiVersion: v1
kind: Pod
metadata:
 name: multi
spec:
 volumes:
 - name: logs-volume
   emptyDir: {}
 - name: outro-volume
   emptyDir: {}
 containers:
 - image: nginx
   name: nginxmulti
   volumeMounts:
   - name: logs-volume
     mountPath: /tmp/a
 - image: busybox
   volumeMounts:
   - name: logs-volume
     mountPath: /tmp/b
   - name: outroVolume
    mountPath: /tmp/logs
   name: busymulti
   command: 
   - sh
   - -c 
   - while true; do sleep 60; done;
