apiVersion: v1
kind: Pod
metadata: 
 name: multi-container
spec:
  volumes:
  - name: logs-volume
    emptyDir: {}
  containers: 
  - name: nginx1
    image: nginx
    volumeMounts:
    - name: logs-volume
      mountPath: /pasta1
  - name: nginxz
    image: nginx
    volumeMounts:
    - name: logs-volume
      mountPath: /pasta2